name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
env:
  TEST_IMAGE_NAME: gh-kubeval-action:${{github.sha}}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn install

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.1.0

      - name: Lint Code
        uses: a-b-r-o-w-n/eslint-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: "src/**/*"
          extensions: ".js,.ts"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - run: yarn install

      - name: Run Jest tests
        uses: mattallty/jest-github-action@v1
        with:
          test-command: "yarn test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
